### ISSUE TITLE
Support for Linux system

### ISSUE THREAD

**Issue by mariogamer2** [koolkdev/wfslib#1]
I'm pretty sure it's already support linux but it give a lot of error while manually compiling.

**Comment by mariogamer2** [comment]
Trying to build with mono xbuild give error with (probably) windows only file.

**Comment by koolkdev** [comment]
Support for linux  (+ makefiles) is on the way. Visual Studio is pretty loosey with the C++ standard, while g++ is strict, so I have to change few things to comply with the standard (which I started to do in the last commit)

**Comment by mariogamer2** [comment]
Thank :)

**Comment by koolkdev** [comment]
I accidentally committed broken Makefile, it is fixed now.

**Comment by mariogamer2** [comment]
There's still proble whle building.

**Comment by mariogamer2** [comment]
There's still some problem while compiling:

https://pastebin.com/ZKdegZkF

**Comment by mariogamer2** [comment]
Even while manually building cryptopp and boostlib

**Comment by mariogamer2** [comment]
It seem like include library dir are not configured to use system path

**Comment by koolkdev** [comment]
According to the log, boost isn't missing, only cryptopp, so you have an issue with that library. It worked for me with installing libcrypto++-dev.

**Comment by koolkdev** [comment]
And it DID find that library, or else it would print another error. maybe some features are disabled in your compilation?)

**Comment by mariogamer2** [comment]
Yeah wasn't sure cause of the type of error.

Maybe. But it doesn't work with libcrypto++-dev....

**Comment by koolkdev** [comment]
sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libcrypto++-dev
make

worked for me on a clean linux machine. If you built it by yourself first you need to make sure that you don't use your compilation.  My code is compiled against shared library , which mean that those functions are missing in the shared library, and librypto++ package has them for sure.
objdump -TC /usr/lib/x86_64-linux-gnu/libcryptopp.so.6  | grep "CryptoPP::Algorithm::Algorithm(bool)"
000000000019b200 g    DF .text	00000000000001a0  Base        CryptoPP::Algorithm::Algorithm(bool)
000000000019b200 g    DF .text	00000000000001a0  Base        CryptoPP::Algorithm::Algorithm(bool)

**Comment by mariogamer2** [comment]
[pid  9003] stat("..//libcryptopp.so", 0x7ffd76fd9250) = -1 ENOENT (No such file or directory)
[pid  9003] open("..//libcryptopp.so", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  9003] stat("..//libcryptopp.a", {st_mode=S_IFREG|0664, st_size=78509710, ...}) = 0
[pid  9003] open("..//libcryptopp.a", O_RDONLY) = 11

Strange.....

**Comment by koolkdev** [comment]
Ok, so it was my error. The issue was with the library order. Since it used a static library (and not shared one as usual) the order was important, because libwfs.a is depends on libcryptopp.a and can't be specified after it. I fixed it now.
