### ISSUE TITLE
make installation failed on mac os 10.14.1

### ISSUE THREAD

**Issue by Spinoni31** [koolkdev/wfslib#10]
tried to install following the instructions on the readme and by adding the extra -o command for wfs-fuse but i got the following error during compile:
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates
MBP-di-Simone:wfslib simonevaleriospinoni$ sudo make -o default_permissions,allow_other
Password:
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C wfslib
c++ -c -Wall -Werror -std=c++14 Area.cpp -o Area.o
In file included from Area.cpp:8:
In file included from ./Area.h:10:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:5: error: 
      destructor called on non-final 'Directory' that has virtual functions but
      non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3617:9: note: 
      in instantiation of member function
      'std::__1::__shared_ptr_emplace<Directory, std::__1::allocator<Directory>
      >::__on_zero_shared' requested here
        __shared_ptr_emplace(_Alloc __a, _Args&& ...__args)
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4277:26: note: 
      in instantiation of function template specialization
      'std::__1::__shared_ptr_emplace<Directory, std::__1::allocator<Directory>
      >::__shared_ptr_emplace<const std::__1::basic_string<char> &, const
      AttributesBlock &, std::__1::shared_ptr<Area>,
      std::__1::shared_ptr<MetadataBlock> >' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4656:29: note: 
      in instantiation of function template specialization
      'std::__1::shared_ptr<Directory>::make_shared<const
      std::__1::basic_string<char> &, const AttributesBlock &,
      std::__1::shared_ptr<Area>, std::__1::shared_ptr<MetadataBlock> >'
      requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
Area.cpp:53:14: note: in instantiation of function template specialization
      'std::__1::make_shared<Directory, const std::__1::basic_string<char> &,
      const AttributesBlock &, std::__1::shared_ptr<Area>,
      std::__1::shared_ptr<MetadataBlock> >' requested here
        return std::make_shared<Directory>(name, attributes, shared_from...
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3656:23: note: 
      qualify call to silence this warning
    __data_.second().~_Tp();
                      ^
1 error generated.
make[1]: *** [Area.o] Error 1
make: *** [wfslib] Error 2`.

i'm using xcode 10.1
how can i solve this?

**Comment by Pysis868** [comment]
Also getting this on a Mac.  Lastest code seems to be in the latest release as well, and that passes..

**Comment by 916253** [comment]
getting this as well

**Comment by koolkdev** [comment]
Fixed in commit 4b67e0dc16cf1cfa1111231863c09849eb16cb1c.

There are new instructions for mac, pkg-config is also required now.
