### ISSUE TITLE
Paths with upper case characters are not handled correctly

### ISSUE THREAD

**Issue by jan-hofmeier** [koolkdev/wfslib#13]
Trying to inject a file with a Path that contains upper case character gives a error:
``` bash
/mnt/wfslib/wfs-file-injector/wfs-file-injector --image "/dev/mmcblk1" --inject-file "/ntfs/nus_content/0005001010062200/42/content/Common/lodging/convert_test/WagonMap2/WiiUBg07.szs" --inject-path "sys/title/00050010/10062200/content/Common/lodging/convert_test/WagonMap2/WiiUBg07.szs" --otp "otp.bin" --mlc
Error: Didn't find file sys/title/00050010/10062200/content/Common/lodging/convert_test/WagonMap2/WiiUBg07.szs in wfs
```

Similiar when trying to extract a specific directory, which path contains upper case characters.

Some internal structures (the trees that are traversed in Directory::GetObjectAttributes) seem to use only lower case.

I will provide a patch soon.

**Comment by koolkdev** [comment]
Fixed in v1.1
