### ISSUE TITLE
Makefile Error 2 on Artix Linux (Arch Linux)

### ISSUE THREAD

**Issue by ethancodes2020** [koolkdev/wfslib#15]
I've installed all the stuff needed to compile this on Linux, and I still cannot get it to compile. Looks to be a issue in the code.

make -C wfslib
make[1]: Entering directory '/home/ethan/wfslib/wfslib'
rm -f .depend
g++ -c -Wall -Werror -std=c++14 -MM Area.cpp Block.cpp DataBlock.cpp DeviceEncryption.cpp Directory.cpp File.cpp FileDevice.cpp KeyFile.cpp MetadataBlock.cpp Structs.cpp SubBlockAllocator.cpp Wfs.cpp WfsItem.cpp > .depend
g++ -c -Wall -Werror -std=c++14 Area.cpp -o Area.o
g++ -c -Wall -Werror -std=c++14 Block.cpp -o Block.o
g++ -c -Wall -Werror -std=c++14 DataBlock.cpp -o DataBlock.o
g++ -c -Wall -Werror -std=c++14 DeviceEncryption.cpp -o DeviceEncryption.o
g++ -c -Wall -Werror -std=c++14 Directory.cpp -o Directory.o
g++ -c -Wall -Werror -std=c++14 File.cpp -o File.o
g++ -c -Wall -Werror -std=c++14 FileDevice.cpp -o FileDevice.o
g++ -c -Wall -Werror -std=c++14 KeyFile.cpp -o KeyFile.o
g++ -c -Wall -Werror -std=c++14 MetadataBlock.cpp -o MetadataBlock.o
g++ -c -Wall -Werror -std=c++14 Structs.cpp -o Structs.o
g++ -c -Wall -Werror -std=c++14 SubBlockAllocator.cpp -o SubBlockAllocator.o
g++ -c -Wall -Werror -std=c++14 Wfs.cpp -o Wfs.o
g++ -c -Wall -Werror -std=c++14 WfsItem.cpp -o WfsItem.o
WfsItem.cpp: In member function ‘std::string WfsItem::GetRealName()’:
WfsItem.cpp:41:14: error: ‘runtime_error’ is not a member of ‘std’
   41 |   throw std::runtime_error("Unexepected filename length");
      |              ^~~~~~~~~~~~~
make[1]: *** [Makefile:13: WfsItem.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ethan/wfslib/wfslib'
make: *** [Makefile:21: wfslib] Error 2

My System:

![image](https://user-images.githubusercontent.com/25110919/106653944-742adb00-6565-11eb-96b8-c64cd1c9aa66.png)

**Comment by koolkdev** [comment]
Can you try to replace `#include <exception>` with `#include <stdexcept>` in wfslib/Block.h and see if it fixes that issue?

**Comment by ethancodes2020** [comment]
Works fine now. Thank you so much!
