### ISSUE TITLE
Failed to detect sector size

### ISSUE THREAD

**Issue by wabberz** [koolkdev/wfslib#2]
Hi, I compiled this without any issues on Arch, everything seemed fine, but when I try to mount my USB drive, I get this:

`Error: Wfs: Failed to detect sector size`

wxHexEditor and other tools can read the drive just fine. It's a 1TB HDD if that helps.

**Comment by koolkdev** [comment]
Can you post the output of "sudo fdisk -l" for that device? the sector size.
Right now I assume that it is 512, 2K or 4K.

**Comment by wabberz** [comment]
Sure:

`Disk /dev/sdi: 931,5 GiB, 1000203804160 bytes, 1953523055 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes`

Thanks for the quick reply :smile:

**Comment by koolkdev** [comment]
Ok, that is weird. I see now that I have a bug if the sector size isn't
512. But the sector size in your case is 512.
The error means that it couldn't successfully calculate the hash on the
first block, which means that the IV is probably wrong. And the IV depends
on the sector size and the sectors count of the disk.

Can you print the value of "wfs_header->root_area_attributes.blocks_count.
value() " in wfslib/Wfs.cpp:60?
You can add the line:
std::cout << wfs_header->root_area_attributes.blocks_count.value() << " "
<< block_size << std::endl;
before the line:
device->SetSectorsCount(wfs_header->root_area_attributes.blocks_count.value()
<< (block_size - device->GetLog2SectorSize()));
And maybe #include <iostream> at the begging of the file.
Thanks.

**Comment by wabberz** [comment]
Alright, here's the output:
> 122095190 13
> Error: Wfs: Failed to detect sector size

**Comment by koolkdev** [comment]
Hmm, that seems fine. One option is that the WiiU used another sector size
for some reason.
Can you try to add this line:
```DetectSectorsCount(device, key);```
after this line: (Wfs.cpp:66)
```device->SetLog2SectorSize(sector_size);``` If that was the reason it
should fix it. If it still doesn't work, I can take a look on that block.
If you want that I will do it, can you send me the following things? the
first 8192 bytes of the usb device and the seeprom.

**Comment by wabberz** [comment]
> 122095190 13
> 122095190 13
> 122095190 13
> 122095190 13
> Error: Wfs: Failed to detect sector size
I guess that's a no :unamused: 

How do you want me to send you that data? Is there anything private/sensitive in there I shouldn't share publicly?

**Comment by koolkdev** [comment]
In the first block of the file system there is only file system metadata, nothing personal or sensitive. The first 4 bytes of the usb seed from the seeprom is your console NG ID. (unique id for your console)
If you prefer, you can send it directly to my email: koolkdev [at] gmail.com

**Comment by koolkdev** [comment]
The Issue was that the code assumed that the total number of sectors is divisible by sectors count in one block, but this wasn't true for your device.  So now I properly find those parameters as they are used by the wfs.

**Comment by wabberz** [comment]
Nice, thanks for the quick fix! Glad I could contribute a little info :smile:
