### ISSUE TITLE
Build error on Arch: log2 not declared

### ISSUE THREAD

**Issue by wabberz** [koolkdev/wfslib#3]
> make -C wfslib
> make[1]: Entering directory '/home/user/git/wfslib/wfslib'
> g++ -c -Wall -Werror -std=c++14 Area.cpp -o Area.o
> g++ -c -Wall -Werror -std=c++14 Block.cpp -o Block.o
> g++ -c -Wall -Werror -std=c++14 DataBlock.cpp -o DataBlock.o
> g++ -c -Wall -Werror -std=c++14 DeviceEncryption.cpp -o DeviceEncryption.o
> g++ -c -Wall -Werror -std=c++14 Directory.cpp -o Directory.o
> g++ -c -Wall -Werror -std=c++14 File.cpp -o File.o
> g++ -c -Wall -Werror -std=c++14 FileDevice.cpp -o FileDevice.o
> g++ -c -Wall -Werror -std=c++14 KeyFile.cpp -o KeyFile.o
> g++ -c -Wall -Werror -std=c++14 MetadataBlock.cpp -o MetadataBlock.o
> g++ -c -Wall -Werror -std=c++14 Structs.cpp -o Structs.o
> g++ -c -Wall -Werror -std=c++14 SubBlockAllocator.cpp -o SubBlockAllocator.o
> g++ -c -Wall -Werror -std=c++14 Wfs.cpp -o Wfs.o
> Wfs.cpp: In static member function ‘static void Wfs::DetectDeviceSectorSizeAndCount(const std::shared_ptr<FileDevice>&, const std::vector<unsigned char>&)’:
> Wfs.cpp:87:50: error: ‘log2’ was not declared in this scope
>   device->SetLog2SectorSize(static_cast<uint32_t>(log2(xored_sector_size)));
>                                                   ^~~~
> Wfs.cpp:87:50: note: suggested alternative: ‘long’
>   device->SetLog2SectorSize(static_cast<uint32_t>(log2(xored_sector_size)));
>                                                   ^~~~
>                                                   long
> make[1]: *** [Makefile:14: Wfs.o] Error 1
> make[1]: Leaving directory '/home/user/git/wfslib/wfslib'
> make: *** [Makefile:19: wfslib] Error 2

Now I'm getting this build error. My GCC version is `gcc-Version 7.1.1 20170630 (GCC)`.

**Comment by koolkdev** [comment]
Oops, forgot include and library. But I changed the code, now I doesn't use that function and check that it is really power of 2,

**Comment by wabberz** [comment]
Thanks, I finally got it to work! :smile:
