### ISSUE TITLE
Build issue ‘DetectSectorSize’ and 'DetectSectorsCount’ is not a member of ‘Wfs’

### ISSUE THREAD

**Issue by wolfmankurd** [koolkdev/wfslib#4]
Failes when running make in haxchi-pc-installer, wfslib compiles just fine.

Looks like in wfslib/wfslib/Wfs.cpp there is a DetectDeviceSectorSizeAndCount method not sure if relevent.
 
> g++ -Iwfslib/ -c -Wall -Werror -std=c++14 main.cpp -o main.o
> main.cpp: In function ‘int main(int, char**)’:
> main.cpp:89:3: error: ‘DetectSectorsCount’ is not a member of ‘Wfs’
>    Wfs::DetectSectorsCount(device, key);
>    ^~~
> main.cpp:90:3: error: ‘DetectSectorSize’ is not a member of ‘Wfs’
>    Wfs::DetectSectorSize(device, key);
>    ^~~
> Makefile:19: recipe for target 'main.o' failed
> make: *** [main.o] Error 1

> $ uname -a
> Linux ali-debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

> $ make --version
> GNU Make 4.1
> Built for x86_64-pc-linux-gnu
> Copyright (C) 1988-2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> $ gcc --version
> gcc (Debian 6.3.0-18) 6.3.0 20170516
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Latest sources from git, couldn't do --recursive so explicitly cloned wfslib inside the main directory.

**Comment by koolkdev** [comment]
> Latest sources from git, couldn't do --recursive so explicitly cloned wfslib inside the main directory.

That is the issue, haxchi-pc-installer was built against specific version of wfslib. The wfslib submodule is right now at tag v0.3. So you need to checkout ":v0.3" in wfslib.
