### ISSUE TITLE
Compile error on Ubuntu 16.04

### ISSUE THREAD

**Issue by rmafort** [koolkdev/wfslib#5]
Installed all dependencies.

Here is the bash log:

make[1]: Entering directory '/home/users/rodrigo.mafort/wfslib/wfs-fuse'
g++ -I../ -c -Wall -Werror -std=c++14 -D_FILE_OFFSET_BITS=64 wfs-fuse.cpp -o wfs-fuse.o
wfs-fuse.cpp: In function ‘int wfs_readdir(const char*, void*, fuse_fill_dir_t, off_t, fuse_file_info*)’:
wfs-fuse.cpp:60:57: error: use of ‘item’ before deduction of ‘auto’
  for (auto item : *std::dynamic_pointer_cast<Directory>(item)) {
                                                         ^
Makefile:15: recipe for target 'wfs-fuse.o' failed
make[1]: *** [wfs-fuse.o] Error 1
make[1]: Leaving directory '/home/users/rodrigo.mafort/wfslib/wfs-fuse'
Makefile:19: recipe for target 'wfs-fuse' failed
make: *** [wfs-fuse] Error 2

**Comment by koolkdev** [comment]
ok I fixed it. I wonder why my g++ didn't complain about it. Which version of g++ do you have?

**Comment by rmafort** [comment]
Thanks for fixing it so quickly! My g++ version is 5.4.0
