### ISSUE TITLE
minor text error

### ISSUE THREAD

**Issue by piratesephiroth** [koolkdev/wfslib#6]
https://github.com/koolkdev/wfslib/blob/df51ccc7a7fbd7790c33a08eda78afa9e12013dd/wfs-extract/main.cpp#L78

the command line usage help says "--dump-path" instead of "--output"

**Comment by ihaveamac** [comment]
it says both. because both are valid arguments.
```
  --output arg          ouput directory
  --dump-path arg (=/)  directory to dump (default: "/")
```

**Comment by piratesephiroth** [comment]
nah, --dump-path does not work

**Comment by ihaveamac** [comment]
that's what it does.....it dumps a specific part from the filesystem (e.g. `--dump-path /usr/title/00050000`)

**Comment by piratesephiroth** [comment]
ecks dee
better close this then
