### ISSUE TITLE
Is it possible to skip over a bad hash?

### ISSUE THREAD

**Issue by quinton-ashley** [koolkdev/wfslib#7]
Is it possible to skip a bad hash?  All the other files were extracted properly until it gets into my saves folder.
`Error: Bad hash for block 0x0066DA80`

**Comment by quinton-ashley** [comment]
I've tried a few SD cards now and none of them transfer over the NAND without this bad hash error in the same place.  Is it possible my wii u memory is corrupted at this position or is there an error in this program?  I've looked over the source code and I'm confused about where or if I could implement a skip over this block or the file that contains this block.

**Comment by koolkdev** [comment]
The code until now skipped over files with corrupted data, but in your case the folder block is corrupted. I added in e29934659a578e4dd991078e532ba8f9590acefb that it will skip over corrupted folders, but it won't extract any file from them.

Can your try again with the latest release? (WFS Tools v0.6.46)

**Comment by quinton-ashley** [comment]
It worked!  Thank you!
